### PR TITLE
Added postgresql file

### PR DESCRIPTION
**Pull request by omarsamy09**
1- Added PostgreSQL file in the deployment
2- Added hardware specs in workflow
3- Used DB credentials from k8s secrets
4- Updated environment variables accordingly.

### CODE REVIEW

**Comment by Nilegfx** [comment]
What do you think is missing here to complete the feature?

**Comment by Nilegfx** [comment]
What do you think is missing here to complete the feature?

**Comment by omarsamy09** [comment]
> What do you think is missing here to complete the feature?

I forgot to edit the deployment file

**Comment by Nilegfx** [comment]
correct, you need to ensure that the new db is synced with the old db.

there are some decisions needs to be agreed upon internally among BE team. which exact steps needs to be taken in order to keep our current data safe.

Please go through this discussion and let me know what is your proposed action items/steps/procedure.

**Pull request merged**
